services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"  
    volumes:
      - ./frontend:/app  
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
